headertext: This is my header text
secondlineheader: This is the second line of the header for doing other stuff
primarybuttontext: A button
primarybuttonlink: http://kissmelinda.com
secondarybuttontext: A button
secondarybuttonlink: http://kissmelinda.com
facebooklink: https://nl-nl.facebook.com/AmsterdamCarriages
twitterlink: https://twitter.com/Gerebeer
pinterestlink: http://www.pinterest.com/amscarr/amsterdam-carriages/
rsslink: 
phone: +31 6 24607 426
email: info@carrages.nl
adress: Dam 8
adress1: 1012 NP Amsterdam
adress2: The Netherland
footertext: copyright goes here....
