headertext: This is my header text
secondlineheader: This is the second line of the header for doing other stuff
primarybuttontext: A button
primarybuttonlink: http://kissmelinda.com
secondarybuttontext: A button
secondarybuttonlink: http://kissmelinda.com

