headertext: This is my header text
secondlineheader: This is the second line of the header for doing other stuff
primarybuttontext: A button
primarybuttonlink: http://kissmelinda.com
secondarybuttontext: A button
secondarybuttonlink: http://kissmelinda.com
facebook: favebookuser
twitter: twitteruser
pinterest: pinterestuser
phone: phonenumer
email: emailadress
adress: adress
adress1: adress1
adress2: adress2
footertext: All rights unreserved by 
footertextname: yourname 

